MERGE INTO MPA KEY (RATING_ID, MPA_NAME) VALUES (1, 'G');
MERGE INTO MPA KEY (RATING_ID, MPA_NAME) VALUES (2, 'PG');
MERGE INTO MPA KEY (RATING_ID, MPA_NAME) VALUES (3, 'PG-13');
MERGE INTO MPA KEY (RATING_ID, MPA_NAME) VALUES (4, 'R');
MERGE INTO MPA KEY (RATING_ID, MPA_NAME) VALUES (5, 'NC-17');

MERGE INTO GENRES KEY (GENRE_ID, GENRE_NAME) VALUES (1, 'Комедия');
MERGE INTO GENRES KEY (GENRE_ID, GENRE_NAME) VALUES (2, 'Драма');
MERGE INTO GENRES KEY (GENRE_ID, GENRE_NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRES KEY (GENRE_ID, GENRE_NAME) VALUES (4, 'Фантастика');
MERGE INTO GENRES KEY (GENRE_ID, GENRE_NAME) VALUES (5, 'Ужасы');
MERGE INTO GENRES KEY (GENRE_ID, GENRE_NAME) VALUES (6, 'Мелодрама');