MERGE INTO mpa KEY (RATING_ID, MPA_NAME) VALUES (1, 'G');
MERGE INTO mpa KEY (RATING_ID, MPA_NAME) VALUES (2, 'PG');
MERGE INTO mpa KEY (RATING_ID, MPA_NAME) VALUES (3, 'PG-13');
MERGE INTO mpa KEY (RATING_ID, MPA_NAME) VALUES (4, 'R');
MERGE INTO mpa KEY (RATING_ID, MPA_NAME) VALUES (5, 'NC-17');

MERGE INTO genres KEY (GENRE_ID, GENRE_NAME) VALUES (1, 'Комедия');
MERGE INTO genres KEY (GENRE_ID, GENRE_NAME) VALUES (2, 'Драма');
MERGE INTO genres KEY (GENRE_ID, GENRE_NAME) VALUES (3, 'Мультфильм');
MERGE INTO genres KEY (GENRE_ID, GENRE_NAME) VALUES (4, 'Фантастика');
MERGE INTO genres KEY (GENRE_ID, GENRE_NAME) VALUES (5, 'Ужасы');
MERGE INTO genres KEY (GENRE_ID, GENRE_NAME) VALUES (6, 'Мелодрама');

INSERT INTO FILMS(FILM_NAME, FILM_DESCRIPTION, FILM_RELEASE_DATE, FILM_DURATION, RATING_ID)
VALUES ( 'FILM_NAME', 'FILM_DESCRIPTION', '2000-01-01', 120, 1 );

INSERT INTO FILMS(FILM_NAME, FILM_DESCRIPTION, FILM_RELEASE_DATE, FILM_DURATION, RATING_ID)
VALUES ( 'FILM_NAME2', 'FILM_DESCRIPTION2', '2000-01-01', 90, 2 );

INSERT INTO USERS(USER_EMAIL, USER_LOGIN, USER_NAME, USER_BIRTHDAY)
VALUES ( 'user@mail.ru', 'user_login', 'username', '1986-01-01' );

INSERT INTO USERS(USER_EMAIL, USER_LOGIN, USER_NAME, USER_BIRTHDAY)
VALUES ( 'user2@mail.ru', 'user_login2', 'username2', '1986-01-02' );

INSERT INTO FILM_GENRES(FILM_ID, GENRE_ID) VALUES ( 1, 1 );

INSERT INTO LIKES(FILM_ID, USER_ID) VALUES ( 1 , 1 );

INSERT INTO LIKES(FILM_ID, USER_ID) VALUES ( 1 , 2 );